# config/services.yaml
services:
    _defaults:
        autowire: true          # Automatically injects dependencies in your services.
        autoconfigure: true     # Automatically registers your services as commands, event subscribers, etc.
        public: false           # Allows optimizing the container by removing unused services; this also means
                                # fetching services directly from the container via $container->get() won't work.
                                # The best practice is to be explicit about your dependencies anyway.
        bind:
            #$projectDir: '%kernel.project_dir%'


    PbdKn\ContaoContaohabBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Resources,public,Tests}'

    PbdKn\ContaoContaohabBundle\Controller\:
        resource: '../../Controller/'
        public: true
        tags: ['controller.service_arguments']

    PbdKn\ContaoContaohabBundle\Controller\ImportCohSensorController:
        tags: ['controller.service_arguments']

    PbdKn\ContaoContaohabBundle\Module\ModuleCohCallback:
        public: true

# eventlistener 
    PbdKn\ContaoContaohabBundle\EventListener\BackendStyleListener:
        tags:
          - { name: kernel.event_listener, event: contao.backend.load_data_container, method: __invoke }

#modul ModuleCohThings als service      
    PbdKn\ContaoContaohabBundle\Module\ModuleCohThings:
        arguments:
          $moduleModel: '@contao.framework'
          $column: 'main'
#        tags:
#          - { name: contao.frontend_module, category: "coh" }
          
# logger service logAusschriebe, nur wenn debug modus
    PbdKn\ContaoContaohabBundle\Service\LoggerService:
        public: true
        arguments:
          $dateiname: 'cohdebug.log'
          $contaoLogger: '@monolog.logger.contao'
          $container: '@service_container' # Injiziere den service_container

# Callbackroutinen für globale funktionen in der dca
# in dieser klasse wird der button erstellt
#    PbdKn\ContaoContaohabBundle\DataContainer\CohThings:             
#        tags:
#            - { name: contao.callback }


#    PbdKn\ContaoContaohabBundle\Command\ContaohabDaemonCommand:
#        tags: ['console.command']
        

    PbdKn\ContaoContaohabBundle\Sensor\SensorManager:
        public: true
        arguments:
          $fetchers: !tagged_iterator sensor.fetcher

    PbdKn\ContaoContaohabBundle\Sensor\IQBoxSensorService:
        tags: ['sensor.fetcher']        

    PbdKn\ContaoContaohabBundle\Sensor\TasmotaSensorService:
        tags: ['sensor.fetcher']        

    PbdKn\ContaoContaohabBundle\Sensor\HeizstabSensorService:
        tags: ['sensor.fetcher']        

