<?php

$GLOBALS['TL_DCA']['tl_coh_sensorcollector_settings'] = [
    'config' => [
        'dataContainer' => Contao\DC_Table::class,
        'enableVersioning' => true,
        'sql' => [
            'keys' => ['id' => 'primary'],
        ],
    ],
    'list' => [
        'sorting' => ['mode' => 1, 'fields' => ['id'], 'flag' => 11],
        'label' => ['fields' => ['title'], 'format' => '%s'],
        'global_operations' => ['all' => ['href' => 'act=select', 'class' => 'header_edit_all']],
        'operations' => [
            'edit' => ['href' => 'act=edit', 'icon' => 'edit.svg'],
            'copy' => ['href' => 'act=copy', 'icon' => 'copy.svg'],
            'delete' => ['href' => 'act=delete', 'icon' => 'delete.svg', 'attributes' => 'onclick="if(!confirm(this.dataset.msg))return false;" data-msg="'.($GLOBALS['TL_LANG']['MSC']['deleteConfirm'] ?? '').'"'],
        ],
    ],
    'palettes' => [
        '__selector__' => ['storageProAccess', 'heizstabAccess', 'tasmotaAccess', 'wasserLeckageAccess', 'raspberryAccess'],
        'default' => '{general_legend},title;{storagepro_legend},storageProAccess;{ampere_cl_legend},ampereClUsername,ampereClPassword,ampereClRetries,ampereClRetryDelay,ampereClLifetimeCacheSeconds;{heizstab_legend},heizstabAccess;{tasmota_legend},tasmotaAccess;{wasserleckage_legend},wasserLeckageAccess;{raspberry_api_legend},raspberryAccess',
    ],
    'subpalettes' => [
        'storageProAccess_local' => 'storageProHost,storageProPort,storageProUnitId,storageProTimeout',
        'storageProAccess_raspberry' => 'storageProRaspberryBaseUrl,storageProRaspberryToken,storageProRaspberryPath,storageProRaspberryTimeout,storageProHost,storageProPort,storageProUnitId,storageProTimeout',
        'heizstabAccess_local' => 'heizstabUrl,heizstabAuthEnabled,heizstabLoginPath,heizstabPassword,heizstabPasswordField,heizstabCookieFile,heizstabInsecureTls',
        'heizstabAccess_cloud' => 'heizstabCloudBaseUrl,heizstabCloudSerial,heizstabCloudApiToken',
        'tasmotaAccess_raspberry' => 'tasmotaRaspberryBaseUrl,tasmotaRaspberryToken,tasmotaRaspberryPath,tasmotaRequestTimeout',
        'wasserLeckageAccess_raspberry' => 'wasserLeckageRaspberryBaseUrl,wasserLeckageRaspberryToken,wasserLeckageRaspberryPath,wasserLeckageRequestTimeout',
        'raspberryAccess_local' => 'raspberryApiBaseUrl,raspberryApiToken,raspberryApiPath,raspberryApiTimeout,raspberryApiCacheSeconds',
        'raspberryAccess_http' => 'raspberryApiWanBaseUrl,raspberryApiToken,raspberryApiPath,raspberryApiTimeout,raspberryApiCacheSeconds',
    ],
    'fields' => [
        'id' => ['sql' => "int(10) unsigned NOT NULL auto_increment"],
        'tstamp' => ['sql' => "int(10) unsigned NOT NULL default 0"],
        'title' => ['inputType' => 'text', 'eval' => ['mandatory' => true, 'maxlength' => 128, 'tl_class' => 'w50'], 'sql' => "varchar(128) NOT NULL default ''"],
        'storageProAccess' => [
            'inputType' => 'radio',
            'options' => ['disabled', 'local', 'raspberry'],
            'reference' => &$GLOBALS['TL_LANG']['tl_coh_sensorcollector_settings']['storageProAccessOptions'],
            'eval' => ['mandatory' => true, 'submitOnChange' => true, 'tl_class' => 'clr'],
            'sql' => "varchar(16) NOT NULL default 'local'",
        ],
        'storageProRaspberryBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'http://p1pu92iv4i9yh2m2.myfritz.net'"],
        'storageProRaspberryToken' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'COH_CODE'"],
        'storageProRaspberryPath' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default '/api/coh/iqbox-modbus.php'"],
        'storageProRaspberryTimeout' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'minval' => 1, 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 15"],
        'storageProHost' => ['inputType' => 'text', 'eval' => ['mandatory' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'ASP-HSR2103J2311E08738.local'"],
        'storageProPort' => ['inputType' => 'text', 'eval' => ['mandatory' => true, 'rgxp' => 'natural', 'minval' => 1, 'maxval' => 65535, 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 502"],
        'storageProUnitId' => ['inputType' => 'text', 'eval' => ['mandatory' => true, 'rgxp' => 'natural', 'minval' => 0, 'maxval' => 255, 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 1"],
        'storageProTimeout' => ['inputType' => 'text', 'eval' => ['mandatory' => true, 'rgxp' => 'digit', 'minval' => 1, 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 3"],
        'ampereClUsername' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'ampereClPassword' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'ampereClRetries' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 3"],
        'ampereClRetryDelay' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 10"],
        'ampereClLifetimeCacheSeconds' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "int(10) unsigned NOT NULL default 60"],
        'ampereClTokens' => ['sql' => "blob NULL"],
        // Alte Cloud-Spalten bleiben nur fuer verlustfreie Schema-Updates bestehen.
        'ampereUsername' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'amperePassword' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'ampereRetries' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 3"],
        'ampereRetryDelay' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 10"],
        'lifetimeCacheSeconds' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "int(10) unsigned NOT NULL default 60"],
        'ampereTokens' => ['sql' => "blob NULL"],
        'heizstabAccess' => [
            'inputType' => 'radio',
            'options' => ['disabled', 'local', 'cloud'],
            'reference' => &$GLOBALS['TL_LANG']['tl_coh_sensorcollector_settings']['heizstabAccessOptions'],
            'eval' => ['mandatory' => true, 'submitOnChange' => true, 'tl_class' => 'clr'],
            'sql' => "varchar(16) NOT NULL default 'disabled'",
        ],
        'heizstabAuthEnabled' => ['inputType' => 'checkbox', 'eval' => ['tl_class' => 'w50 m12'], 'sql' => "char(1) NOT NULL default '1'"],
        // Legacy-Spalten bleiben erhalten, damit bestehende Installationen verlustfrei migriert werden.
        'heizstabLocalEnabled' => ['inputType' => 'checkbox', 'eval' => ['tl_class' => 'w50 m12'], 'sql' => "char(1) NOT NULL default '1'"],
        'heizstabUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'heizstabLoginPath' => ['inputType' => 'text', 'eval' => ['maxlength' => 128, 'tl_class' => 'w50'], 'sql' => "varchar(128) NOT NULL default '/auth.jsn'"],
        'heizstabPassword' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'heizstabPasswordField' => ['inputType' => 'text', 'eval' => ['maxlength' => 64, 'tl_class' => 'w50'], 'sql' => "varchar(64) NOT NULL default 'pw'"],
        'heizstabCookieFile' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'vendor/pbd-kn/contao-contaohab-bundle/contao/config/heizstabCookieFile.txt'"],
        'heizstabInsecureTls' => ['inputType' => 'checkbox', 'eval' => ['tl_class' => 'w50 m12'], 'sql' => "char(1) NOT NULL default ''"],
        'heizstabCloudEnabled' => ['inputType' => 'checkbox', 'eval' => ['tl_class' => 'w50 m12'], 'sql' => "char(1) NOT NULL default ''"],
        'heizstabCloudBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'https://api.my-pv.com/api/v1'"],
        'heizstabCloudSerial' => ['inputType' => 'text', 'eval' => ['maxlength' => 64, 'tl_class' => 'w50'], 'sql' => "varchar(64) NOT NULL default ''"],
        'heizstabCloudApiToken' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'raspberryApiEnabled' => ['inputType' => 'checkbox', 'eval' => ['tl_class' => 'w50 m12'], 'sql' => "char(1) NOT NULL default ''"],
        'raspberryAccess' => [
            'inputType' => 'radio',
            'options' => ['disabled', 'local', 'http'],
            'reference' => &$GLOBALS['TL_LANG']['tl_coh_sensorcollector_settings']['raspberryAccessOptions'],
            'eval' => ['mandatory' => true, 'submitOnChange' => true, 'tl_class' => 'clr'],
            'sql' => "varchar(16) NOT NULL default 'disabled'",
        ],
        // Legacy-Feld fuer die Migration bestehender Installationen.
        'raspberryApiBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'http://192.168.178.49'"],
        'raspberryApiToken' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default ''"],
        'raspberryApiWanBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'http://p1pu92iv4i9yh2m2.myfritz.net'"],
        'raspberryApiTimeout' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 10"],
        'raspberryApiPath' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default '/api/coh/raspberry-status.php'"],
        'tasmotaAccess' => [
            'inputType' => 'radio',
            'options' => ['disabled', 'local', 'raspberry'],
            'reference' => &$GLOBALS['TL_LANG']['tl_coh_sensorcollector_settings']['tasmotaAccessOptions'],
            'eval' => ['mandatory' => true, 'submitOnChange' => true, 'tl_class' => 'clr'],
            'sql' => "varchar(16) NOT NULL default 'local'",
        ],
        'tasmotaRaspberryBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'http://p1pu92iv4i9yh2m2.myfritz.net'"],
        'tasmotaRaspberryToken' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'COH_CODE'"],
        'tasmotaRaspberryPath' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default '/api/coh/tasmota.php'"],
        'tasmotaRequestTimeout' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 15"],
        'wasserLeckageAccess' => [
            'inputType' => 'radio',
            'options' => ['disabled', 'local', 'raspberry'],
            'reference' => &$GLOBALS['TL_LANG']['tl_coh_sensorcollector_settings']['wasserLeckageAccessOptions'],
            'eval' => ['mandatory' => true, 'submitOnChange' => true, 'tl_class' => 'clr'],
            'sql' => "varchar(16) NOT NULL default 'local'",
        ],
        'wasserLeckageRaspberryBaseUrl' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'http://p1pu92iv4i9yh2m2.myfritz.net'"],
        'wasserLeckageRaspberryToken' => ['inputType' => 'text', 'eval' => ['hideInput' => true, 'maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default 'COH_CODE'"],
        'wasserLeckageRaspberryPath' => ['inputType' => 'text', 'eval' => ['maxlength' => 255, 'tl_class' => 'w50'], 'sql' => "varchar(255) NOT NULL default '/api/coh/wasserleckage.php'"],
        'wasserLeckageRequestTimeout' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "smallint(5) unsigned NOT NULL default 15"],
        'raspberryApiCacheSeconds' => ['inputType' => 'text', 'eval' => ['rgxp' => 'natural', 'tl_class' => 'w50'], 'sql' => "int(10) unsigned NOT NULL default 15"],
    ],
];
